- job:
    name: update
    project-type: pipeline
    sandbox: true
    defaults: global
    pipeline-scm:
      scm:
        - git:
            url: https://github.com/tmoody1/CI_Pipeline.git
            clean: true
      script-path: docker/jenkins/jobs/update.groovy
