version: '3.2'

services:
  main:
    image: sonarqube
    ports:
      - 9000:9000
    volumes:
      - "sonar_home:/opt/sonarqube"
    networks:
      - docker

volumes:
  sonar_home:
networks:
  docker:
