version: '3.2'

services:
  mysql:
    image: mysql:5.6
    container_name: trainer-app
    networks:
      - app
    env_file:
      ./secrets.txt
  tracker:
    image: trainer/trainer-tracker
    ports:
      - 9090:8080
    networks:
      - app
networks:
  app: