- name: create a disk
  gcp_compute_disk:
      name: "disk-instance"
      size_gb: 10
      source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
      zone: us-west1-a
      project: "{{ project }}"
      auth_kind: "{{ auth_kind }}"
      service_account_file: "{{ service_account_file }}"
      state: "{{ state }}"
      scopes: "{{ scopes }}"
  register: disk

- name: create a network
  gcp_compute_network:
      name: "network-instance"
      project: "{{ project }}"
      auth_kind: "{{ auth_kind }}"
      service_account_file: "{{ service_account_file }}"
      state: "{{ state }}"
      scopes: "{{ scopes }}"
  register: network

- name: create a address
  gcp_compute_address:
      name: "address-instance"
      region: us-west1
      project: "{{ project }}"
      auth_kind: "{{ auth_kind }}"
      service_account_file: "{{ service_account_file }}"
      state: "{{ state }}"
      scopes: "{{ scopes }}"
  register: address



- name: create a instance
  gcp_compute_instance:
      name: "infra"
      machine_type: f1-micro
      disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
      network_interfaces:
      - network: "{{ network }}"
        access_configs:
        - name: External NAT
          nat_ip: "{{ address }}"
          type: ONE_TO_ONE_NAT
      zone: us-west1-a
      project: "{{ project }}"
      auth_kind: "{{ auth_kind }}"
      service_account_file: "{{ service_account_file }}"
      scopes: "{{ scopes }}"
      state: "{{ state }}"
      metadata:
        istest: true

- name: create a firewall
  gcp_compute_firewall:
      name: "infra_firewall"
      allowed:
      - ip_protocol: tcp
        ports:
        - '22'
      target_tags:
      - infra
      source_ranges:
      - 0.0.0.0/0
      project: "{{ project }}"
      auth_kind: "{{ auth_kind }}"
      service_account_file: "{{ service_account_file }}"
      state: "{{ state }}"

- name: Wait for ssh to come up
  wait_for: host="{{ address }}" port=22 delay=10  timeout=300

- name: install docker
  apt:
    name: docker-ce
  delegate_to: "{{ address }}"
