---
- name: Allocate an IP Address
  gcp_compute_address:
    state: absent
    name: 'test-address1'
    project: "{{ gcp_project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    scopes: "{{ scopes }}"
    region: "{{ region }}"