version: '3.2'

services:
  main:
    image: jenkins-ci
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - type: "volume"
        source: jenkins_home
        target: /var/jenkins_home
        volume:
          nocopy: true
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    env_file:
      ./secrets.txt

volumes:
  jenkins_home:
