---

- hosts: all
  become: yes
  roles:
    - app
  vars:
    region: 'us-west1'
    gcp_project: "gleaming-store-226116"
    auth_kind: "serviceaccount"
    service_account_file: "/home/tmoody/google/key/key.json"
    scopes:
      - "https://www.googleapis.com/auth/compute"
