- name: Create IP address
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_file: /home/tmoody/google/key/key.json
    project: gleaming-store-226116
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:

   - name: Allocate an IP Address
     gcp_compute_address:
         state: absent
         name: 'test-address1'
         region: 'us-west1'
         project: "{{ project }}"
         auth_kind: "{{ auth_kind }}"
         service_account_file: "{{ service_account_file }}"
         scopes: "{{ scopes }}"